/* FICHIER: data.js */

const songsData = [
    { id: 1, movie: "Leo", title: "Naa Ready", file: "naa_ready.mp3" },
    { id: 2, movie: "Leo", title: "Badass", file: "badass.mp3" },
    { id: 3, movie: "The GOAT", title: "Whistle Podu", file: "whistle_podu.mp3" },
    { id: 4, movie: "Master", title: "Vaathi Coming", file: "vaathi_coming.mp3" },
    { id: 5, movie: "Master", title: "Vaathi Raid", file: "vaathi_raid.mp3" },
    { id: 6, movie: "Beast", title: "Arabic Kuthu", file: "arabic_kuthu.mp3" },
    { id: 7, movie: "Varisu", title: "Ranjithame", file: "ranjithame.mp3" },
    { id: 8, movie: "Bigil", title: "Verithanam", file: "verithanam.mp3" },
    { id: 9, movie: "Mersal", title: "Aalaporan Thamizhan", file: "aalaporan.mp3" },
    { id: 10, movie: "Sarkar", title: "Simtaangaran", file: "simtaangaran.mp3" },
    { id: 11, movie: "Kaththi", title: "Selfie Pulla", file: "selfie_pulla.mp3" },
    { id: 12, movie: "Kaththi", title: "Theme Music", file: "kaththi_theme.mp3" },
    { id: 13, movie: "Theri", title: "Jithu Jilladi", file: "jithu_jilladi.mp3" },
    { id: 14, movie: "Thuppakki", title: "Google Google", file: "google_google.mp3" },
    { id: 15, movie: "Thuppakki", title: "Antarctica", file: "antarctica.mp3" },
    { id: 16, movie: "Nanban", title: "Ask Laska", file: "ask_laska.mp3" },
    { id: 17, movie: "Velayudham", title: "Chillax", file: "chillax.mp3" },
    { id: 18, movie: "Kaavalan", title: "Step Step", file: "step_step.mp3" },
    { id: 19, movie: "Vettaikaaran", title: "Puli Urumudhu", file: "puli_urumudhu.mp3" },
    { id: 20, movie: "Villu", title: "Daddy Mummy", file: "daddy_mummy.mp3" },
    { id: 21, movie: "Pokkiri", title: "Aadungada", file: "aadungada.mp3" },
    { id: 22, movie: "Pokkiri", title: "Pokkiri Pongal", file: "pokkiri_pongal.mp3" },
    { id: 23, movie: "ATM", title: "Ellappugazhum", file: "ellappugazhum.mp3" },
    { id: 24, movie: "Ghilli", title: "Appadi Podu", file: "appadi_podu.mp3" },
    { id: 25, movie: "Ghilli", title: "Arjunaru Villu", file: "arjunaru_villu.mp3" },
    { id: 26, movie: "Thirumalai", title: "Vaadiyamma", file: "vaadiyamma.mp3" },
    { id: 27, movie: "Sivakasi", title: "Kodambakkam Area", file: "kodambakkam.mp3" },
    { id: 28, movie: "Sachein", title: "Vaadi Vaadi", file: "vaadi_vaadi.mp3" },
    { id: 29, movie: "Youth", title: "Aal Thotta Boopathi", file: "aal_thotta.mp3" },
    { id: 30, movie: "Kushi", title: "Kattipudi Kattipudida", file: "kattipudi.mp3" }
];

const punchesData = [
    { movie: "Pokkiri", text: "Oru vaati mudivu panitenna, en pecha naane kekka maaten." },
    { movie: "Thuppakki", text: "Andha Baayam Irukanom Daaa..." },
    { movie: "Kaththi", text: "10 Nimusathula Motha Peru Vandila Irukanum, Vandi Areaku Veliya Irukanum" },
    { movie: "Bigil", text: "Cup mukkiyam Bigil-u!" },
    { movie: "Mersal", text: "Sillakhi Dummaa..." },
    { movie: "Leo", text: "Bloody Sweet." },
    { movie: "Theri", text: "Twinkle Twinkle Little Star" },
    { movie: "Sarkar", text: "I am not a corporate criminal. I am the CEO." },
    { movie: "Ghilli", text: "All area layum aiya ghilli da." },
    { movie: "Thirumalai", text: "Vazhkai Oru Vattam Daaa...Inga Jeikkaravan Thopan, Thokaravan Jeipaan.." },
    { movie: "Vettaikaran", text: "Saami Munaadi Daan Shaanthama Pesuven. Sakaada Munaadi Ilai" },
    { movie: "Kuruvi", text: "Namma Paechu Mattum Daan Silent Ah Irukum, Aana Adi Saravedi." },
    { movie: "Master", text: "Enna maathanum-nu nenaikatha... Enaku koda pudikatha." },
    { movie: "Jilla", text: "Sakthi illama yevanum illai..." },
    { movie: "Beast", text: "Meaner, Leaner, Stronger." },
    { movie: "Azhagiya Tamizh Magan", text: "Evulavo Pannurom, Idha Panamattoma." },
    { movie: "Nanban", text: "All Is Well..." },
];

const emojiData = [
    { emojis: "🦁 🍫 ❄️", answer: "Leo" },
    { emojis: "👓 🔫 💣", answer: "Thuppakki" },
    { emojis: "⚽ 🏟️ 👨‍👦", answer: "Bigil" },
    { emojis: "💉 🎩 🐂", answer: "Mersal" },
    { emojis: "🍺 🏫 🤜", answer: "Master" },
    { emojis: "🏢 🗳️ 👔", answer: "Sarkar" },
    { emojis: "💧 👴 💰", answer: "Kaththi" },
    { emojis: "👻 👮 🥐", answer: "Theri" },
    { emojis: "👮 🕵️ 🥥", answer: "Pokkiri" },
    { emojis: "🏃 💡 🛖", answer: "Ghilli" },
    { emojis: "🏰 🐢 ⚔️", answer: "Puli" },
    { emojis: "🏬 ✈️ 🥷", answer: "Beast" },
    { emojis: "🤝 🔨 🧱", answer: "Friends" },
    { emojis: "🚕 🔧 🚬", answer: "Thirumalai" },
    { emojis: "🧨 🎆 👕", answer: "Sivakasi" },
    { emojis: "🚄 ✈️ 🏠", answer: "Varisu" },
    { emojis: "👽 🦸 🥛", answer: "Velayudham" },
    { emojis: "🎓 ⛹️ 🐆", answer: "Kuruvi" },
    { emojis: "🏹 ⛪ 💀", answer: "Villu" },
    { emojis: "🚉 🔪 🚩", answer: "Kushi" },
    { emojis: "🛥️ 🎣 🌊", answer: "Sura" },
    { emojis: "💼 ⚖️ 🧠", answer: "Thamizhan" },
    { emojis: "🎭 🚌 🌧️", answer: "Priyamanavale" },
    { emojis: "🐐 🧬 ⏳", answer: "The GOAT" }
];